name: ghostsystem
channels:
  - conda-forge
  - defaults
dependencies:
  - numba
  - pip
  - python
  - python-socketio
  - sanic
  - bitarray
  - cgal
  - swig
  - cmake
  - python-devtools
  - libgcc-ng
  - cxx-compiler
  #  - python-cgal-bindings
  - pip:
      - esper==1.3
      - psycopg2-binary
#      - cgal-bindings