name: ghostsystem
channels:
  - conda-forge
  - defaults
dependencies:
  - numba
  - pip
  - python=3.8.*
  - python-socketio
  - sanic
  - bitarray
  - pip:
      - esper==1.3
      - psycopg2-binary